
name: CI

on:
  push:
    branches: [ master,develop ]
  pull_request:
    branches: [ master,develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name : Build
      run: npm run-script prepare
    - name: Test
      run: npm test

